import 'package:intl/intl.dart';
import '../models/budget.dart';
import '../models/expense.dart';
import '../widgets/category_definitions.dart';

class BudgetService {
  List<Budget> generateAutoBudgetsFromIncome({
    required double avgMonthlyIncome,
    required DateTime month,
  }) {
    final budgets = <Budget>[];
    if (avgMonthlyIncome <= 0) {
      return budgets;
    }
    final startMonth = DateFormat('yyyy-MM').format(month);
    final allocations = _incomeAllocation();
    for (final category in expenseCategories.map((e) => e.label)) {
      final percent = allocations[category] ?? 0;
      if (percent <= 0) {
        continue;
      }
      final limit = avgMonthlyIncome * percent;
      budgets.add(Budget(
        category: category,
        monthlyLimit: double.parse(limit.toStringAsFixed(2)),
        startMonth: startMonth,
        autoGenerated: true,
      ));
    }
    return budgets;
  }

  Map<String, double> _incomeAllocation() {
    return {
      'Shopping': 0.08,
      'Food': 0.14,
      'Travel': 0.07,
      'Health': 0.08,
      'Education': 0.08,
      'Transport': 0.07,
      'Home': 0.22,
      'Bills': 0.16,
      'Other': 0.10,
    };
  }
}
