class Budget {
  int? id;
  final String category;
  final double monthlyLimit;
  final String startMonth;
  final bool autoGenerated;
  final DateTime? createdAt;

  Budget({
    this.id,
    required this.category,
    required this.monthlyLimit,
    required this.startMonth,
    required this.autoGenerated,
    this.createdAt,
  });

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'category': category,
      'monthly_limit': monthlyLimit,
      'start_month': startMonth,
      'auto_generated': autoGenerated ? 1 : 0,
      'created_at': (createdAt ?? DateTime.now()).toIso8601String(),
    };
  }

  factory Budget.fromMap(Map<String, dynamic> map) {
    return Budget(
      id: map['id'],
      category: map['category'],
      monthlyLimit: map['monthly_limit'],
      startMonth: map['start_month'],
      autoGenerated: (map['auto_generated'] ?? 0) == 1,
      createdAt: map['created_at'] != null ? DateTime.parse(map['created_at']) : null,
    );
  }
}