import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../database/app_database.dart';
import '../models/budget.dart';
import '../models/expense.dart';
import '../services/budget_service.dart';
import '../services/analytics_service.dart';
import '../services/auth_service.dart';
import '../widgets/category_definitions.dart';
import '../widgets/currency.dart';

class BudgetsScreen extends StatefulWidget {
  final List<Expense> expenses;
  final String currencySymbol;

  const BudgetsScreen({
    super.key,
    required this.expenses,
    required this.currencySymbol,
  });

  @override
  State<BudgetsScreen> createState() => _BudgetsScreenState();
}

class _BudgetsScreenState extends State<BudgetsScreen> {
  late Future<List<Budget>> _budgetsFuture;

  @override
  void initState() {
    super.initState();
    _reload();
  }

  void _reload() {
    _budgetsFuture = AppDatabase().getBudgets();
  }

  Future<void> _generateAutoBudgets() async {
    final income = await AuthService().getAvgMonthlyIncome();
    final budgets = BudgetService().generateAutoBudgetsFromIncome(
      avgMonthlyIncome: income,
      month: DateTime.now(),
    );
    await AppDatabase().clearBudgets();
    for (final budget in budgets) {
      await AppDatabase().addBudget(budget);
    }
    setState(_reload);
  }

  Future<void> _editBudget(Budget budget) async {
    final controller = TextEditingController(text: budget.monthlyLimit.toStringAsFixed(0));
    final newLimit = await showDialog<double>(
      context: context,
      builder: (context) => AlertDialog(
        title: Text('Edit ${budget.category}'),
        content: TextField(
          controller: controller,
          keyboardType: TextInputType.number,
          decoration: const InputDecoration(labelText: 'Monthly limit'),
        ),
        actions: [
          TextButton(onPressed: () => Navigator.pop(context), child: const Text('Cancel')),
          TextButton(
            onPressed: () {
              final value = double.tryParse(controller.text.replaceAll(',', ''));
              Navigator.pop(context, value);
            },
            child: const Text('Save'),
          ),
        ],
      ),
    );
    if (newLimit != null) {
      final updated = Budget(
        id: budget.id,
        category: budget.category,
        monthlyLimit: newLimit,
        startMonth: budget.startMonth,
        autoGenerated: false,
        createdAt: budget.createdAt,
      );
      await AppDatabase().updateBudget(updated);
      setState(_reload);
    }
  }

  @override
  Widget build(BuildContext context) {
    final monthKey = DateFormat('yyyy-MM').format(DateTime.now());
    final analytics = AnalyticsService();
    final totals = analytics.categoryTotals(widget.expenses, DateTime.now());

    return FutureBuilder<List<Budget>>(
      future: _budgetsFuture,
      builder: (context, snapshot) {
        final budgets = (snapshot.data ?? [])
            .where((b) => b.startMonth == monthKey)
            .toList();
        return ListView(
          padding: const EdgeInsets.fromLTRB(20, 16, 20, 120),
          children: [
            Row(
              children: [
                const Expanded(
                  child: Text(
                    'Budgets',
                    style: TextStyle(fontSize: 24, fontWeight: FontWeight.w800),
                  ),
                ),
                TextButton(
                  onPressed: _generateAutoBudgets,
                  child: const Text('Auto Generate'),
                ),
              ],
            ),
            const SizedBox(height: 12),
            if (budgets.isEmpty)
              _EmptyBudgetCard(onGenerate: _generateAutoBudgets)
            else
              ...budgets.map((budget) {
                final spent = totals[budget.category] ?? 0;
                final ratio = budget.monthlyLimit == 0
                    ? 0.0
                    : (spent / budget.monthlyLimit).clamp(0.0, 1.0);
                final category = categoryByLabel(budget.category);
                return GestureDetector(
                  onTap: () => _editBudget(budget),
                  child: Container(
                    margin: const EdgeInsets.only(bottom: 12),
                    padding: const EdgeInsets.all(16),
                    decoration: BoxDecoration(
                      color: Theme.of(context).colorScheme.surface,
                      borderRadius: const BorderRadius.all(Radius.circular(18)),
                    ),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Row(
                          children: [
                            Icon(category?.icon ?? Icons.category, color: category?.color),
                            const SizedBox(width: 12),
                            Expanded(
                              child: Text(
                                budget.category,
                                style: const TextStyle(fontWeight: FontWeight.w700),
                              ),
                            ),
                            Text(
                              CurrencyFormatter.format(budget.monthlyLimit, widget.currencySymbol),
                              style: const TextStyle(fontWeight: FontWeight.w700),
                            ),
                          ],
                        ),
                        const SizedBox(height: 12),
                        ClipRRect(
                          borderRadius: BorderRadius.circular(12),
                          child: LinearProgressIndicator(
                            value: ratio,
                            minHeight: 8,
                            backgroundColor: Theme.of(context).colorScheme.onSurface.withOpacity(0.1),
                            valueColor: AlwaysStoppedAnimation<Color>(
                              ratio > 0.9
                                  ? Theme.of(context).colorScheme.error
                                  : Theme.of(context).colorScheme.secondary,
                            ),
                          ),
                        ),
                        const SizedBox(height: 8),
                        Text(
                          'Spent ${CurrencyFormatter.format(spent, widget.currencySymbol)}',
                          style: TextStyle(color: Theme.of(context).colorScheme.onSurface.withOpacity(0.6)),
                        ),
                      ],
                    ),
                  ),
                );
              }),
          ],
        );
      },
    );
  }
}

class _EmptyBudgetCard extends StatelessWidget {
  final VoidCallback onGenerate;

  const _EmptyBudgetCard({required this.onGenerate});

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    return Container(
      padding: const EdgeInsets.all(18),
      decoration: BoxDecoration(
        color: scheme.surface,
        borderRadius: const BorderRadius.all(Radius.circular(18)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text('No budgets yet', style: TextStyle(fontWeight: FontWeight.w700)),
          const SizedBox(height: 8),
          Text(
            'Generate budgets based on your recent spending.',
            style: TextStyle(color: scheme.onSurface.withOpacity(0.7)),
          ),
          const SizedBox(height: 12),
          OutlinedButton(
            onPressed: onGenerate,
            child: const Text('Generate Budgets'),
          ),
        ],
      ),
    );
  }
}
